version: "3.9"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    networks:
      - sipia_rv1_4
    container_name: account-api-con
    hostname: account-api
    restart: on-failure

networks:
  sipia_rv1_4:
    name: sipia_rv1_4
    driver: bridge
