version: "3.9"

services:
  account-service:
    build: .
    ports:
      - "8080:8080"
    networks:
      - account-service-network
    container_name: account-api-con
    hostname: account-api
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 50M

networks:
  account-service-network:
    name: account-service-network
    driver: bridge
    external: true
